#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ListViewSample.Resource", IsApplication=true)]

namespace ListViewSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040006
			public const int assignmentblue = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int assignmentgrey = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int assignmentoffwhite = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int blueassignmentbutton = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int blueclick = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int confirmationborder = 2130968586;
			
			// aapt resource value: 0x7f04000d
			public const int disabledText = 2130968589;
			
			// aapt resource value: 0x7f040002
			public const int greybutton = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int greyheadertext = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int greyspinnertext = 2130968579;
			
			// aapt resource value: 0x7f04000c
			public const int historycolor = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int itemssearchcolor = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int listviewdivider = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int navigationitemselected = 2130968584;
			
			// aapt resource value: 0x7f04000e
			public const int radio_selector_color = 2130968590;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int accept = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int accept_assignment = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AcceptedAssignmentIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int action_bar_back = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int actionbar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int active_assignment_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ActiveAssignmentIcon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int assignment_list_selector = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int back_button = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bottomSearchBar = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cameraIcon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int clearIcon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int clearIconDown = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int darkPhoneIcon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int decline = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int decline_assignment = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int documentIcon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int downlaborhours = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int EnrouteImage = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int HoldImage = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Icon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ItemPopupDivider = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int labordescriptionbottom = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int laborHoursBottom = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int LaborHoursDivider = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int loginbox = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int MapIcon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int MapOverlayDirections = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int MapOverlayDirectionsDown = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int MapOverlayDivider = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int MapOverlayIcon = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int MapOverlayIconDown = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int navigationIcon = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int NewAssignmentIcon = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int NextButton = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int PhoneIcon = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int PreviousButton = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int questionmark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int roundedblack = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int SearchIcon = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int SelectedItem = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int SummaryPause = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int SummaryRecord = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int timer_selector = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int TimerPause = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int TimerRecord = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int TrashCanIcon = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int triangleblue = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int triangledark = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int trianglegrey = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int trianglewhite = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int UpLaborHours = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int XamarinTitle = 2130837556;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070014
			public const int TimerLayout = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int accept_decline_Layout = 2131165203;
			
			// aapt resource value: 0x7f070008
			public const int assignmentAccept = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int assignmentAddress = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int assignmentDecline = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int assignmentItemNumber = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int assignmentJob = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int assignmentMapIcon = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int assignmentName = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int assignmentPhone = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int assignmentPhoneIcon = 2131165189;
			
			// aapt resource value: 0x7f070015
			public const int assignmentSelectedItem = 2131165205;
			
			// aapt resource value: 0x7f07000b
			public const int assignmentStatus = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int assignmentStatusImage = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int assignmentTimer = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int assignmentTimerText = 2131165196;
			
			// aapt resource value: 0x7f070016
			public const int mainLayoutTestListView = 2131165206;
			
			// aapt resource value: 0x7f07000f
			public const int refText1 = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int refText2 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int refText3 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int refText4 = 2131165202;
			
			// aapt resource value: 0x7f07000e
			public const int referenceLayout = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int relativeLayout1 = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AssignmentItemLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainLayoutTest = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int Accept = 2131034118;
			
			// aapt resource value: 0x7f05001e
			public const int AddExpense = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int AddItem = 2131034141;
			
			// aapt resource value: 0x7f05000c
			public const int AddLabor = 2131034124;
			
			// aapt resource value: 0x7f050014
			public const int AddPhoto = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int AddSignature = 2131034133;
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f05001b
			public const int Camera = 2131034139;
			
			// aapt resource value: 0x7f05000e
			public const int Cancel = 2131034126;
			
			// aapt resource value: 0x7f05001a
			public const int Clear = 2131034138;
			
			// aapt resource value: 0x7f050016
			public const int Complete = 2131034134;
			
			// aapt resource value: 0x7f050028
			public const int Confirmations = 2131034152;
			
			// aapt resource value: 0x7f050007
			public const int Decline = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int Delete = 2131034127;
			
			// aapt resource value: 0x7f050017
			public const int DeletePhoto = 2131034135;
			
			// aapt resource value: 0x7f050027
			public const int Documents = 2131034151;
			
			// aapt resource value: 0x7f05001f
			public const int DollarSign = 2131034143;
			
			// aapt resource value: 0x7f050018
			public const int Done = 2131034136;
			
			// aapt resource value: 0x7f050022
			public const int EnterDescription = 2131034146;
			
			// aapt resource value: 0x7f050009
			public const int Expenses = 2131034121;
			
			// aapt resource value: 0x7f05001c
			public const int Gallery = 2131034140;
			
			// aapt resource value: 0x7f050021
			public const int GoogleMapsAPIKey = 2131034145;
			
			// aapt resource value: 0x7f050029
			public const int GoogleMapsKeyIssue = 2131034153;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050026
			public const int History = 2131034150;
			
			// aapt resource value: 0x7f05000d
			public const int HoursAbbrev = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int Items = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int LaborHours = 2131034123;
			
			// aapt resource value: 0x7f050025
			public const int Map = 2131034149;
			
			// aapt resource value: 0x7f050005
			public const int MapTab = 2131034117;
			
			// aapt resource value: 0x7f050023
			public const int OptionalCaption = 2131034147;
			
			// aapt resource value: 0x7f050003
			public const int Password = 2131034115;
			
			// aapt resource value: 0x7f050012
			public const int Photo = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int Photos = 2131034129;
			
			// aapt resource value: 0x7f050019
			public const int PleaseSign = 2131034137;
			
			// aapt resource value: 0x7f050004
			public const int PriorityTab = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int Save = 2131034128;
			
			// aapt resource value: 0x7f050020
			public const int Search = 2131034144;
			
			// aapt resource value: 0x7f050013
			public const int Signature = 2131034131;
			
			// aapt resource value: 0x7f050024
			public const int Summary = 2131034148;
			
			// aapt resource value: 0x7f050002
			public const int Username = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int Xamarin = 2131034120;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int CustomDialogTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int CustomHoloTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
